version: '3.9'

services:
  postgresql:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql_scripts:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

volumes:
  db_data:
