-- REALIZANDO UMA COMPRA --
-- INICIANDO VENDA COM O CLIENTE 1 E O FUNCIONARIO 2
SELECT
  INICIAR_VENDA (1, 2);

-- TENTANDO CONFIRMAR VENDA MAS NEGANDO
-- MOTIVO: NENHUM PRODUTO RELACIONADO
SELECT
  CONFIRMAR_VENDA (1);

-- REGISTRANDO 1 WHEY PROTEIN NA COMPRA 1
SELECT
  REGISTRAR_PRODUTO_NA_COMPRA (1, 1, 1);

-- CONFIRMANDO A COMPRA 1 (ADICIONANDO DATA FINAL E MUDANDO O STATUS)
SELECT
  CONFIRMAR_VENDA (1);

-- REALIZANDO UM CANCELAMENTO
-- INICIANDO VENDA COM O CLIENTE 1 E O FUNCIONARIO 2
SELECT
  INICIAR_VENDA (1, 2);

-- CANCELANDO VENDA 2
SELECT
  CANCELAR_VENDA (2);

-- VIEW PARA VISUALIZAR MELHOR AS VENDAS:
SELECT
  *
FROM
  INFORMACOES_VENDAS
ORDER BY
  ID_VENDA;