-- Função para obter todas as vendas realizadas dentro de um período
CREATE OR REPLACE FUNCTION RELATORIO_VENDAS(
    DATA_INICIO DATE,
    DATA_FIM DATE
)
RETURNS TABLE(
    ID_VENDA INT,
    ID_CLIENTE INT,
    ID_FUNCIONARIO INT,
    DATA_VENDA DATE,
    VALOR_TOTAL DECIMAL(10, 2),
    STATUS VARCHAR(20)
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        V.ID_VENDA,
        V.ID_CLIENTE,
        V.ID_FUNCIONARIO,
        V.DT_VENDA :: DATE,
        V.VALOR_TOTAL,
        V.STATUS
    FROM VENDA V
    WHERE V.DT_VENDA BETWEEN DATA_INICIO AND DATA_FIM;
END;
$$ LANGUAGE plpgsql;
